/* ============================================================
   EXERCISE BANK. Counts are derived, never written here —
   `tools/verify.py` runs every SQL and Python solution against
   real SQLite and real pandas. Run it before shipping content.
   `data` names which preview table to show above the editor, so
   the rows you are querying are visible while you write.
   Every SQL / Excel / Python solution here is machine-verified.
   ============================================================ */
const EX = {
'sql-0':[
 {task:'Return <code>name</code> and <code>salary</code> for everyone in the Data department earning more than 80000, highest salary first.',
  solution:"SELECT name, salary FROM employees WHERE department='Data' AND salary > 80000 ORDER BY salary DESC;",
  hint:'Two conditions joined by AND, then ORDER BY … DESC.', data:'employees'},
 {task:'Return <code>name</code> and <code>city</code> for everyone based in Berlin, sorted alphabetically by name.',
  solution:"SELECT name, city FROM employees WHERE city='Berlin' ORDER BY name;",
  hint:"ORDER BY on a text column sorts A–Z by default — no DESC needed.", data:'employees'},
 {task:'Find the three lowest-paid people in the company. Return <code>name</code>, <code>department</code>, <code>salary</code>, cheapest first.',
  solution:"SELECT name, department, salary FROM employees ORDER BY salary LIMIT 3;",
  hint:'No WHERE at all here — sort ascending and cut the list with LIMIT.', data:'employees'},
 {task:'Return <code>name</code>, <code>city</code> and <code>department</code> for everyone based in Berlin or Milan, sorted by city then name.',
  solution:"SELECT name, city, department FROM employees WHERE city IN ('Berlin','Milan') ORDER BY city, name;",
  hint:'IN is shorter than two conditions joined by OR, and reads better as the list grows.', data:'employees'},
 {task:'Who is still early in their career? Return <code>name</code>, <code>department</code> and <code>years_exp</code> for anyone with fewer than 3 years, least experienced first.',
  solution:"SELECT name, department, years_exp FROM employees WHERE years_exp < 3 ORDER BY years_exp, name;",
  hint:'A second column in ORDER BY breaks ties — without it, equal values come back in whatever order the engine likes.', data:'employees'},
 {task:'Return <code>name</code>, <code>department</code> and <code>salary</code> for everyone <em>outside</em> Engineering earning at least 70000, highest first.',
  solution:"SELECT name, department, salary FROM employees WHERE department <> 'Engineering' AND salary >= 70000 ORDER BY salary DESC;",
  hint:'<> is not-equal. And >= includes exactly 70000, where > would silently drop it.', data:'employees'},
],
'sql-1':[
 {task:'One row per department with <code>name</code>, a <code>headcount</code> that is 0 for empty departments, and the <code>head_count_budget</code>. Sort by headcount, highest first.',
  solution:"SELECT d.name, COUNT(e.id) AS headcount, d.head_count_budget FROM departments d LEFT JOIN employees e ON e.department=d.name GROUP BY d.name, d.head_count_budget ORDER BY headcount DESC;",
  hint:'If Finance vanished you used INNER JOIN; if it shows 1 you used COUNT(*).', data:'employees+departments'},
 {task:'Return <code>department</code> and <code>avg_salary</code> (rounded to 0 decimals) for departments whose average salary is above 70000. Highest average first.',
  solution:"SELECT department, ROUND(AVG(salary),0) AS avg_salary FROM employees GROUP BY department HAVING AVG(salary) > 70000 ORDER BY avg_salary DESC;",
  hint:'You cannot filter an aggregate in WHERE — that is what HAVING is for.', data:'employees'},
 {task:'From <code>orders</code>, return <code>country</code>, the number of orders as <code>orders</code>, and total revenue as <code>revenue</code> (quantity × unit_price). Biggest revenue first.',
  solution:"SELECT country, COUNT(*) AS orders, SUM(quantity*unit_price) AS revenue FROM orders GROUP BY country ORDER BY revenue DESC;",
  hint:'You can put an expression inside SUM(). Revenue is not a stored column.', data:'orders'},
 {task:'Your manager wants a headcount and an average salary for each department, biggest teams first. Round the average to a whole number.',
  solution:"SELECT department, COUNT(*) AS people, ROUND(AVG(salary)) AS avg_salary FROM employees GROUP BY department ORDER BY people DESC, department;",
  hint:'COUNT(*) and AVG() in the same SELECT, grouped by department. Sort on the count, then the name to break ties.', data:'employees'},
 {task:'Compare each department&rsquo;s budgeted headcount against how many people it actually has &mdash; <strong>including departments with nobody in them</strong>. Return the department name, its budget, and the actual count.',
  solution:"SELECT d.name, d.head_count_budget, COUNT(e.id) AS actual FROM departments d LEFT JOIN employees e ON e.department = d.name GROUP BY d.name, d.head_count_budget ORDER BY d.name;",
  hint:'An inner join would hide the empty department entirely. LEFT JOIN keeps it, and COUNT of the joined column gives 0 rather than 1.', data:'employees'},
 {task:'Which countries brought in more than 3000 in revenue? Return <code>country</code> and total revenue (quantity times unit price), rounded to 2 decimals, highest first.',
  solution:"SELECT country, ROUND(SUM(quantity * unit_price), 2) AS revenue FROM orders GROUP BY country HAVING SUM(quantity * unit_price) > 3000 ORDER BY revenue DESC;",
  hint:'WHERE filters rows before grouping; HAVING filters the groups after. A total cannot exist until the group does.', data:'orders'},
],
'sql-2':[
 {task:'Return the single highest-paid person per department — <code>name</code>, <code>department</code>, <code>salary</code> — sorted by department name.',
  solution:"WITH r AS (SELECT name, department, salary, ROW_NUMBER() OVER (PARTITION BY department ORDER BY salary DESC) AS rn FROM employees) SELECT name, department, salary FROM r WHERE rn=1 ORDER BY department;",
  hint:'Rank inside a CTE, filter to rank 1 outside. Four departments have staff.', data:'employees'},
 {task:'For every employee return <code>name</code>, <code>department</code>, <code>salary</code>, and <code>gap</code> — their salary minus their own department average, rounded to 0. Sort by gap, largest first.',
  solution:"SELECT name, department, salary, ROUND(salary - AVG(salary) OVER (PARTITION BY department), 0) AS gap FROM employees ORDER BY gap DESC;",
  hint:'AVG(...) OVER (PARTITION BY department) puts the group average on every row without collapsing them.', data:'employees'},
 {task:'From <code>orders</code>, return the top 2 orders by revenue within each category: <code>category</code>, <code>customer</code>, <code>revenue</code>. Sort by category, then revenue descending.',
  solution:"WITH r AS (SELECT category, customer, quantity*unit_price AS revenue, ROW_NUMBER() OVER (PARTITION BY category ORDER BY quantity*unit_price DESC) AS rn FROM orders) SELECT category, customer, revenue FROM r WHERE rn<=2 ORDER BY category, revenue DESC;",
  hint:'Same CTE shape as the first exercise, but partitioned by category and filtered to rn <= 2.', data:'orders'},
 {task:'Rank everyone by salary <em>within</em> their own department. Return <code>name</code>, <code>department</code>, <code>salary</code> and the rank, ordered by department then rank.',
  solution:"SELECT name, department, salary, RANK() OVER (PARTITION BY department ORDER BY salary DESC) AS dept_rank FROM employees ORDER BY department, dept_rank;",
  hint:'PARTITION BY restarts the ranking for each department, which is the whole reason to use a window here instead of GROUP BY.', data:'employees'},
 {task:'Show how far each person sits from their own department&rsquo;s average salary. Return <code>name</code>, <code>department</code>, <code>salary</code> and the rounded difference, best-paid relative to their team first.',
  solution:"SELECT name, department, salary, ROUND(salary - AVG(salary) OVER (PARTITION BY department)) AS vs_dept_avg FROM employees ORDER BY department, vs_dept_avg DESC;",
  hint:'The window average is computed per row without collapsing it — this is the thing GROUP BY cannot do.', data:'employees'},
 {task:'Build a running revenue total across the year. Return <code>order_date</code>, that order&rsquo;s amount, and the cumulative total to that date. Use a CTE for the per-order amount.',
  solution:"WITH rev AS (SELECT order_date, quantity * unit_price AS amount FROM orders) SELECT order_date, amount, ROUND(SUM(amount) OVER (ORDER BY order_date), 2) AS running_total FROM rev ORDER BY order_date;",
  hint:'A window with ORDER BY and no PARTITION accumulates over the whole set, in that order.', data:'orders'},
],

'python-0':[
 {task:'Print the total revenue, then the number of unique regions — one per line.',
  solution:"print(df['revenue'].sum())\nprint(df['region'].nunique())", expect:"4840\n2",
  hint:'.sum() on the revenue column, .nunique() on the region column.', data:'py-sales'},
 {task:'Print the highest single revenue value, then the number of rows in the frame — one per line.',
  solution:"print(df['revenue'].max())\nprint(len(df))", expect:"1899\n4",
  hint:'.max() on the column; len(df) gives the row count.', data:'py-sales'},
 {task:'Print the mean revenue rounded to one decimal place.',
  solution:"print(round(df['revenue'].mean(), 1))", expect:"1210.0",
  hint:'Wrap .mean() in round() with 1 as the second argument.', data:'py-sales'},
 {task:'Print how many rows the frame has, then how many columns &mdash; one per line.',
  solution:"print(len(df))\nprint(len(df.columns))", expect:"4\n3",
  hint:'len(df) counts rows. df.columns is the column index, so len() of it counts columns.', data:'py-sales'},
 {task:'Print the lowest single revenue figure, then the name of the rep who booked it &mdash; one per line.',
  solution:"print(df['revenue'].min())\nprint(df.loc[df['revenue'].idxmin(), 'rep'])", expect:"594\nLuca",
  hint:'.idxmin() gives the row label of the smallest value; .loc then reads another column from that row.', data:'py-sales'},
 {task:'Print the column names as a plain Python list.',
  solution:"print(list(df.columns))", expect:"['rep', 'region', 'revenue']",
  hint:'Printing df.columns directly shows an Index object. Wrapping it in list() gives the plain list.', data:'py-sales'},
],
'python-1':[
 {task:'Clean the frame — drop duplicate order ids, fill the missing price with the median, add a revenue column — then print the total revenue rounded to 2 decimals.',
  solution:"df2 = df.drop_duplicates(subset=['order_id'])\ndf2['price'] = df2['price'].fillna(df2['price'].median())\ndf2['revenue'] = df2['units'] * df2['price']\nprint(round(df2['revenue'].sum(), 2))", expect:"3190.0",
  hint:'Deduplicate first, then fill. Filling first changes the median from 249.0 to 149.25.', data:'py-orders'},
 {task:'Print how many rows remain after dropping duplicate <code>order_id</code> values.',
  solution:"print(len(df.drop_duplicates(subset=['order_id'])))", expect:"4",
  hint:'One order id appears twice, so one row goes.', data:'py-orders'},
 {task:'Print how many missing values the <code>price</code> column contains.',
  solution:"print(df['price'].isna().sum())", expect:"1",
  hint:'.isna() gives booleans; .sum() counts the True values.', data:'py-orders'},
 {task:'This export contains a duplicated row. Print how many rows are left once exact duplicates are removed.',
  solution:"print(len(df.drop_duplicates()))", expect:"4",
  hint:'.drop_duplicates() returns a new frame — it does not modify df in place unless you assign it back.', data:'py-orders'},
 {task:'Print how many values are missing in the <code>price</code> column.',
  solution:"print(df['price'].isna().sum())", expect:"1",
  hint:'.isna() gives True/False per row; summing booleans counts the Trues.', data:'py-orders'},
 {task:'Treat every missing price as 0 and print the total value of the order lines (units times price).',
  solution:"print((df['units'] * df['price'].fillna(0)).sum())", expect:"3535.0",
  hint:'Without fillna the missing price makes that row NaN, and it drops out of the total silently.', data:'py-orders'},
],
'python-2':[
 {task:'Print total revenue per region, sorted from highest to lowest.',
  solution:"print(df.groupby('region')['revenue'].sum().sort_values(ascending=False))",
  expect:"region\nSouth    3499\nEast     2983\nNorth    1341\nName: revenue, dtype: int64",
  hint:'groupby, sum, then .sort_values(ascending=False).', data:'py-regions'},
 {task:'Print total revenue per category.',
  solution:"print(df.groupby('category')['revenue'].sum())",
  expect:"category\nHW    4144\nSW    3679\nName: revenue, dtype: int64",
  hint:'Same shape as the last one, grouping on the other column.', data:'py-regions'},
 {task:'Print the name of the single region with the highest total revenue.',
  solution:"print(df.groupby('region')['revenue'].sum().idxmax())", expect:"South",
  hint:'.idxmax() returns the index label of the largest value, not the value itself.', data:'py-regions'},
 {task:'Print total revenue broken down by region <em>and</em> category.',
  solution:"print(df.groupby(['region','category'])['revenue'].sum())",
  expect:"region  category\nEast    HW          1498\n        SW          1485\nNorth   HW           747\n        SW           594\nSouth   HW          1899\n        SW          1600\nName: revenue, dtype: int64",
  hint:'Pass a list to groupby for more than one key. The result has a two-level index.', data:'py-regions'},
 {task:'Print the average revenue per category, rounded to one decimal place.',
  solution:"print(df.groupby('category')['revenue'].mean().round(1))",
  expect:"category\nHW    1381.3\nSW    1226.3\nName: revenue, dtype: float64",
  hint:'.round(1) applies to the whole Series after the aggregation.', data:'py-regions'},
 {task:'Your stakeholder wants regions down the side and categories across the top, with revenue in the cells. Print that table.',
  solution:"print(df.pivot_table(index='region', columns='category', values='revenue', aggfunc='sum'))",
  expect:"category    HW    SW\nregion              \nEast      1498  1485\nNorth      747   594\nSouth     1899  1600",
  hint:'pivot_table turns one grouping key into columns — the same numbers as a groupby, in the shape people actually ask for.', data:'py-regions'},
],

'excel-0':[
 {task:'Return the <b>average</b> of the Revenue column (F2:F11).',
  solution:"=AVERAGE(F2:F11)", expect:1306.3,
  hint:'AVERAGE works exactly like SUM. Revenue is column F, rows 2 to 11.', data:'sheet'},
 {task:'Return the <b>total number of units</b> sold — the sum of column D.',
  solution:"=SUM(D2:D11)", expect:76,
  hint:'Same function, different column. Units is column D.', data:'sheet'},
 {task:'Return the revenue for the first row by multiplying its Units and Price cells directly — not by reading column F.',
  solution:"=D2*E2", expect:747,
  hint:'Two cell references and a multiplication sign. No function needed.', data:'sheet'},
],
'excel-1':[
 {task:'Sum the Revenue column (F2:F11) for rows where Region (A2:A11) is <code>South</code>.',
  solution:'=SUMIF(A2:A11, "South", F2:F11)', expect:5242,
  hint:'SUMIF takes three arguments: the range to test, the criteria, the range to add up.', data:'sheet'},
 {task:'Count how many rows have a Category (C2:C11) of <code>Hardware</code>.',
  solution:'=COUNTIF(C2:C11, "Hardware")', expect:4,
  hint:'COUNTIF needs only two arguments — there is nothing to add up.', data:'sheet'},
 {task:'Use a lookup to find <b>Elena</b>\'s revenue. Search the Rep column and return her Revenue.',
  solution:'=VLOOKUP("Elena", B2:F11, 5, FALSE)', expect:2560,
  hint:'The table starts at column B, so Revenue (column F) is the 5th column of that range.', data:'sheet'},
],
'excel-2':[
 {task:'Return the <b>largest</b> value in the Revenue column, rounded to zero decimals.',
  solution:"=ROUND(MAX(F2:F11), 0)", expect:2560,
  hint:'Nest MAX inside ROUND, with 0 as ROUND\'s second argument.', data:'sheet'},
 {task:'Return the <b>median</b> revenue. Note how it differs from the average — that gap is what a skewed distribution looks like.',
  solution:"=MEDIAN(F2:F11)", expect:1491.5,
  hint:'One function, one range. Compare it with the 1306.3 average from earlier.', data:'sheet'},
 {task:'Return the average revenue for the <code>North</code> region only, rounded to 2 decimals.',
  solution:'=ROUND(AVERAGEIF(A2:A11, "North", F2:F11), 2)', expect:660.33,
  hint:'AVERAGEIF takes the same three arguments as SUMIF. Wrap the whole thing in ROUND.', data:'sheet'},
],

'r-0':[
 {task:'Write a pipeline that keeps only rows with <code>salary &gt;= 82000</code>, then returns the mean salary in a column named <code>avg_salary</code>.',
  solution:"staff %>%\n  filter(salary >= 82000) %>%\n  summarise(avg_salary = mean(salary))",
  hint:'filter first, then summarise with a named argument.', data:'r-staff'},
 {task:'Return the staff table sorted by salary, highest first, showing only <code>name</code> and <code>salary</code>.',
  solution:"staff %>%\n  select(name, salary) %>%\n  arrange(desc(salary))",
  hint:'Two verbs. desc() goes inside arrange().', data:'r-staff'},
 {task:'Add a column <code>band</code> that reads "high" when salary is at least 90000 and "standard" otherwise.',
  solution:"staff %>%\n  mutate(band = if_else(salary >= 90000, \"high\", \"standard\"))",
  hint:'mutate creates the column; if_else(condition, true_value, false_value) fills it.', data:'r-staff'},
],
'r-1':[
 {task:'Turn the example into a sorted bar chart of salary by name, with a title. Use <code>geom_col()</code>.',
  solution:"ggplot(staff, aes(x = reorder(name, salary), y = salary)) +\n  geom_col() +\n  coord_flip() +\n  labs(title = \"Salary by employee\", x = NULL, y = \"Salary (EUR)\") +\n  theme_minimal()",
  hint:'reorder(name, salary) sorts the bars; coord_flip() makes long labels readable.', data:'r-staff'},
 {task:'Write a histogram of salary with 5 bins, labelled axes and a title.',
  solution:"ggplot(staff, aes(x = salary)) +\n  geom_histogram(bins = 5) +\n  labs(title = \"Distribution of salary\", x = \"Salary (EUR)\", y = \"Count\") +\n  theme_minimal()",
  hint:'A histogram takes only an x aesthetic — ggplot counts the rows for you.', data:'r-staff'},
 {task:'Explain in your own words why <code>geom_smooth(method = "lm", se = FALSE)</code> can mislead a reader, and when you would keep the band.',
  solution:"se = FALSE hides the confidence band, so a line fitted to very few\npoints looks as authoritative as one fitted to thousands. The line\nalone communicates a trend without communicating how uncertain\nthat trend is.\n\nKeep the band whenever the reader might act on the slope, or\nwhenever n is small. Drop it only when the uncertainty is already\nstated elsewhere and the band genuinely obscures the data.",
  hint:'Think about what the shaded region tells the reader that the line alone does not.', data:'r-staff'},
],
'r-2':[
 {task:'Extend the model to include <code>dept</code> as a second predictor, then print the summary.',
  solution:"model2 <- lm(salary ~ years_exp + dept, data = staff)\nsummary(model2)",
  hint:'Add predictors with +. R turns the text column into indicator variables for you.', data:'r-staff'},
 {task:'A stakeholder reads R-squared 0.76 and says "so experience explains 76% of salary." Write what you would say back.',
  solution:"R-squared is the share of variance explained by the model in this\nsample — not a causal claim, and not a guarantee it generalises.\n\nThree things to say: the model is fitted on 15 observational rows,\nso the estimate is imprecise; experience is likely correlated with\nother things we did not measure (role, seniority, location), so\nsome of that 76% belongs to them; and R-squared on training data\nrises whenever you add predictors, so it cannot by itself tell you\nthe model is good. A held-out RMSE would say more.",
  hint:'Separate three ideas: sample size, confounding, and what R-squared does not measure.', data:'r-staff'},
 {task:'Write the code to split the data, fit on the training half, and compute RMSE on the held-out half.',
  solution:"set.seed(42)\nidx   <- sample(seq_len(nrow(staff)), size = 0.7 * nrow(staff))\ntrain <- staff[idx, ]\ntest  <- staff[-idx, ]\n\nmodel <- lm(salary ~ years_exp, data = train)\npreds <- predict(model, newdata = test)\nrmse  <- sqrt(mean((preds - test$salary)^2))\nrmse",
  hint:'set.seed makes the split reproducible — without it your number changes every run.', data:'r-staff'},
],

'pbi-0':[
 {task:'Name the four cleaning steps you would apply to a monthly sales export where months sit across columns, and say why unpivoting matters.',
  solution:"Promote headers, set explicit column types, remove error and blank\nrows, and unpivot the month columns into two columns: Month and\nValue.\n\nUnpivoting matters because visuals and time intelligence need one\nrow per observation. Twelve month columns cannot be plotted as a\nsingle time series or filtered by a date slicer.",
  hint:'The reshaping step is the one with a specific name — what turns wide into long?', data:'pbi-wide'},
 {task:'A date column arrives as text like <code>14/01/2024</code> and sorts wrongly. Say where you fix it and why not downstream.',
  solution:"Fix it in Power Query, at the Changed Type step, setting the column\nto Date with the correct locale — the export is day-first, so a\ndefault US parse silently turns 14/01 into an error and 03/04 into\nthe wrong day.\n\nNot downstream, because sort order, date slicers and every time\nintelligence function depend on a real date type. A DAX workaround\nre-parses the same text on every query and has to be repeated in\nevery measure. Fixing it once at load means the whole model is\ncorrect by construction.",
  hint:'Think about which fix runs once and which one you have to repeat forever.', data:'pbi-wide'},
 {task:'Explain the difference between a star schema and one flat wide table, and name one concrete thing that breaks with the flat table.',
  solution:"A star schema puts events in a central fact table and attributes in\nsmall dimension tables joined to it. A flat table repeats every\nattribute on every row.\n\nWhat breaks: a slicer on a dimension that has no rows in the fact\ntable. With a Country dimension you can show all countries and see\nwhich ones had zero sales. Flattened, a country with no orders has\nno row at all, so it silently disappears from the slicer and from\nevery total — the same failure as INNER JOIN dropping the empty\ndepartment in the SQL lesson.",
  hint:'The failure is the same one the LEFT JOIN lesson was about.', data:'pbi-wide'},
],
'pbi-1':[
 {task:'Configure the builder so it answers "which category earns the most, and how has revenue moved through the year?" Then say why that is the right set.',
  solution:"A card for total revenue, a bar chart of revenue by category sorted\ndescending, and a line chart of revenue by month.\n\nThree visuals, one question each. The card answers 'how much', the\nbar answers 'where from', the line answers 'which direction'.\nAnything more competes for the same attention without adding an\nanswer.",
  hint:'Two questions were asked, plus a headline number. Three visuals, not nine.', data:'pbi-orders'},
 {task:'Turn on the pie chart and look at it. Write down what specifically fails, and what you would use instead.',
  solution:"Seven countries means seven slices, and people cannot compare\nangles — you can see the largest, but not rank third against\nfourth, which is usually the actual question.\n\nUse a horizontal bar chart sorted descending. Length is compared\naccurately, labels fit, and rank is immediately readable. Keep a\npie only for two or three parts of a genuine whole.",
  hint:'Try to rank the middle slices by eye. Notice how long it takes.', data:'pbi-orders'},
 {task:'A director wants "everything on one page" — 14 visuals. Write the pushback and what you would ship instead.',
  solution:"Fourteen visuals is not one answer, it is fourteen invitations to\nlook. The page ends up read as decoration.\n\nWhat I would ship: one page with the three or four numbers tied to\na decision they actually make, and a second page with the detail,\nreachable by drill-through. The ask behind 'everything on one\npage' is usually 'I do not want to hunt' — solved by hierarchy and\na clear path, not by density.",
  hint:'Address the need behind the request, not the literal request.', data:'pbi-orders'},
],
'pbi-2':[
 {task:'Write a measure giving each category\'s share of total revenue, and explain why <code>ALL</code> is required.',
  solution:"Category Share % =\nDIVIDE(\n    [Revenue],\n    CALCULATE([Revenue], ALL(Sales[category]))\n)\n\nALL removes the category filter from the denominator only, so it\nstays the grand total while the numerator stays filtered to the\ncurrent row's category. Without ALL both sides are filtered\nidentically and every row returns 100%.\n\nUse DIVIDE, not '/', because DIVIDE returns blank rather than an\nerror when the denominator is zero.",
  hint:'The numerator is filtered, the denominator must not be. One function removes a filter.', data:'pbi-orders'},
 {task:'Your total revenue card shows the same number for every region no matter which slicer is clicked. Diagnose it and give the fix.',
  solution:"It is a calculated column, not a measure. A calculated column is\nevaluated once per row when the data loads and stored, so it has no\nfilter context at query time and cannot react to a slicer.\n\nFix: rewrite it as a measure.\n\n    Revenue = SUMX(Sales, Sales[quantity] * Sales[unit_price])\n\nThe measure is evaluated in whatever filter context the visual\nsits in, so clicking a region recalculates it for that region.\nRule of thumb: if it aggregates, make it a measure.",
  hint:'The clue is *when* the value was computed, not what it computes.', data:'pbi-orders'},
 {task:'Write a year-on-year growth measure, and name the one thing that must exist in the model or it silently returns blank.',
  solution:"Revenue PY =\nCALCULATE([Revenue], SAMEPERIODLASTYEAR('Calendar'[Date]))\n\nYoY % =\nDIVIDE([Revenue] - [Revenue PY], [Revenue PY])\n\nWhat must exist: a dedicated Calendar table with one row per date,\ncontinuous with no gaps, marked as the model's date table and\nrelated to the fact table. Every time intelligence function walks\nthat table.\n\nWithout it, or with gaps in it, SAMEPERIODLASTYEAR returns blank\nrather than raising an error — so the visual shows empty cells and\nnothing tells you why.",
  hint:'Time intelligence fails quietly, not loudly. What is it walking over?', data:'pbi-orders'},
],
};

/* Preview tables shown above each editor, so the rows are visible
   while you write the answer. */
const PREVIEW = {
  employees:{title:'employees — 15 rows',
    cols:['id','name','department','salary','years_exp','city'],
    rows:[[1,'Amira Haddad','Data',82000,4,'Berlin'],[2,'Luca Ferrari','Data',96000,7,'Milan'],
          [3,'Sara Novak','Data',61000,1,'Prague'],[4,'Tom Bakker','Engineering',105000,8,'Amsterdam'],
          [5,'Yuki Tanaka','Engineering',88000,5,'Berlin'],[6,'Omar Bensalem','Engineering',72000,3,'Tunis']],
    note:'First 6 of 15. Departments: Data, Engineering, Sales, Marketing.'},
  'employees+departments':{title:'departments — 5 rows',
    cols:['id','name','head_count_budget','office'],
    rows:[[1,'Data',6,'Berlin'],[2,'Engineering',10,'Amsterdam'],[3,'Sales',8,'Milan'],
          [4,'Marketing',5,'London'],[5,'Finance',4,'Paris']],
    note:'All 5 rows. Finance has no employees — that is the point of the exercise. Join on departments.name = employees.department.'},
  orders:{title:'orders — 15 rows',
    cols:['order_id','customer','country','category','quantity','unit_price','order_date'],
    rows:[[1001,'Aurora Ltd','Germany','Hardware',3,249.0,'2024-01-14'],
          [1002,'Beacon SA','France','Software',12,49.5,'2024-01-22'],
          [1003,'Corvus BV','Netherlands','Hardware',1,1899.0,'2024-02-03'],
          [1004,'Delta SRL','Italy','Services',5,320.0,'2024-02-11'],
          [1005,'Aurora Ltd','Germany','Software',30,49.5,'2024-02-19']],
    note:'First 5 of 15. There is no revenue column — compute quantity * unit_price.'},
  'py-sales':{title:'df — 4 rows',
    cols:['rep','region','revenue'],
    rows:[['Amira','North',747],['Luca','North',594],['Sara','South',1899],['Tom','South',1600]],
    note:'The whole frame. Defined for you in the editor — just write the lines that print.'},
  'py-orders':{title:'df — 5 rows',
    cols:['order_id','units','price'],
    rows:[[1,3,'249.0'],[2,12,'49.5'],[2,12,'49.5'],[3,1,'NaN'],[4,5,'320.0']],
    note:'The whole frame. Order 2 is duplicated and order 3 has no price — both deliberate.'},
  'py-regions':{title:'df — 6 rows',
    cols:['region','category','revenue'],
    rows:[['North','HW',747],['North','SW',594],['South','HW',1899],
          ['South','SW',1600],['East','HW',1498],['East','SW',1485]],
    note:'The whole frame. Three regions, two categories.'},
  sheet:{title:'Sheet1 — the live grid below',
    cols:['A Region','B Rep','C Category','D Units','E Price','F Revenue'],
    rows:[['North','Amira','Hardware',3,249,747],['North','Luca','Software',12,49.5,594],
          ['South','Sara','Hardware',1,1899,1899]],
    note:'Row 1 is the header, so data runs from row 2 to row 11. Full grid shown below the formula bar.'},
  'r-staff':{title:'staff — 4 rows',
    cols:['name','dept','salary','years_exp'],
    rows:[['Amira','Data',82000,4],['Luca','Data',96000,7],['Sara','Data',61000,1],['Mei','Data',118000,11]],
    note:'The whole frame, mirroring the SQL employees table so you can compare the two languages.'},
  'pbi-wide':{title:'sales_export.csv — as received',
    cols:['Region','Jan','Feb','Mar','Apr'],
    rows:[['North',747,594,1341,880],['South',1899,1600,3499,1204],['East',1498,1485,2983,1610]],
    note:'Months across columns instead of down rows. This shape cannot be plotted as a time series until it is unpivoted.'},
  'pbi-orders':{title:'Sales — 15 rows aggregated in the builder',
    cols:['category','revenue','country','month'],
    rows:[['Hardware',747,'Germany','01'],['Software',594,'France','01'],
          ['Hardware',1899,'Netherlands','02'],['Services',1600,'Italy','02']],
    note:'First 4 of 15. Seven countries in total — worth remembering when you look at the pie.'},
};

/* Python starter frames, injected so the exercise is about the
   operation, not about retyping the data. */
const PY_SETUP = {
  'py-sales':"import pandas as pd\n\ndf = pd.DataFrame({\n    'rep': ['Amira','Luca','Sara','Tom'],\n    'region': ['North','North','South','South'],\n    'revenue': [747, 594, 1899, 1600]\n})\n",
  'py-orders':"import pandas as pd\nimport numpy as np\n\ndf = pd.DataFrame({\n    'order_id': [1, 2, 2, 3, 4],\n    'units': [3, 12, 12, 1, 5],\n    'price': [249.0, 49.5, 49.5, np.nan, 320.0]\n})\n",
  'py-regions':"import pandas as pd\n\ndf = pd.DataFrame({\n    'region': ['North','North','South','South','East','East'],\n    'category': ['HW','SW','HW','SW','HW','SW'],\n    'revenue': [747, 594, 1899, 1600, 1498, 1485]\n})\n",
};

/* Varied success copy — the same sentence every time stops being
   information after the third read. */
const WINS = ['Correct.','That works.','Right answer.','Exactly right.','Solved.','Nailed it.','Correct — clean solution.','That is the one.'];
const win = () => WINS[Math.floor(Math.random()*WINS.length)];
